final List<Map<String, dynamic>> foodItems = [
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description':
        'Classic Fried Chicken Meal sjashasjhsdsgcshgksdkscghgshgsdghjsgchjdshjgdjsajgadsfhj',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
  {
    'imageUrl': 'assets/images/kfc 2.png',
    'description': 'Classic Fried Chicken Meal',
    'price': '40.00',
    'rating': '4.5',
    'quantity': 10,
  },
  {
    'imageUrl': 'assets/images/kelewele 1.png',
    'description': 'Spaghetti Bolognese',
    'price': '30.00',
    'rating': '4.0',
    'quantity': 5,
  },
  {
    'imageUrl': 'assets/images/Yam.png',
    'description': 'Beef Burger',
    'price': '25.00',
    'rating': '4.7',
    'quantity': 8,
  },
];
